-- 实验数据库只保存合成数据，不包含任何真实用户信息。
CREATE DATABASE IF NOT EXISTS sre_lab;
USE sre_lab;

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    customer_email VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    total_amount DECIMAL(12, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- 使用数字笛卡尔积一次性生成 100,000 行，避免逐行 INSERT 导致初始化过慢。
-- BAD 版本故意不创建 customer_email 索引，配合前导通配 LIKE 稳定触发全表扫描。
INSERT INTO orders (customer_email, status, total_amount, created_at)
SELECT
    CONCAT('customer-', n, IF(MOD(n, 10) = 0, '@slow.example.com', '@example.com')),
    ELT(MOD(n, 4) + 1, 'CREATED', 'PAID', 'SHIPPED', 'CANCELLED'),
    MOD(n * 137, 50000) / 100,
    NOW() - INTERVAL MOD(n, 43200) SECOND
FROM (
    SELECT ones.n + tens.n * 10 + hundreds.n * 100 + thousands.n * 1000 + ten_thousands.n * 10000 AS n
    FROM (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones
    CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tens
    CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) hundreds
    CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) thousands
    CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ten_thousands
) generated_rows
WHERE NOT EXISTS (SELECT 1 FROM orders LIMIT 1);

-- 创建只读诊断账号。Agent 的 MySQL Tool 只使用此账号，并在代码层再次限制 SELECT/EXPLAIN。
CREATE USER IF NOT EXISTS 'sre_reader'@'%' IDENTIFIED BY 'sre_reader_dev_only';
GRANT SELECT, SHOW VIEW, PROCESS ON *.* TO 'sre_reader'@'%';
FLUSH PRIVILEGES;
