kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sre-lab
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 18080
    protocol: TCP
  - containerPort: 30081
    hostPort: 18081
    protocol: TCP
  - containerPort: 30082
    hostPort: 18082
    protocol: TCP
  - containerPort: 30083
    hostPort: 18083
    protocol: TCP
  - containerPort: 30090
    hostPort: 19090
    protocol: TCP
  - containerPort: 30306
    hostPort: 13307
    protocol: TCP
  - containerPort: 30201
    hostPort: 19200
    protocol: TCP
  - containerPort: 30601
    hostPort: 15601
    protocol: TCP
  - containerPort: 30800
    hostPort: 12800
    protocol: TCP
  - containerPort: 30801
    hostPort: 11800
    protocol: TCP
  - containerPort: 30912
    hostPort: 19412
    protocol: TCP
  - containerPort: 30808
    hostPort: 18088
    protocol: TCP
