import{randomUUID}from"node:crypto";import type{CreatePayment,Payment}from"../models/payment.js";import{NotificationClient}from"../clients/notification-client.js";import{PaymentRepository}from"../repositories/payment-repository.js";import{config}from"../config/config.js";import{leakedBytes,log}from"../observability/telemetry.js";

/** Application service owns payment state transitions and controlled memory behavior. */
export class PaymentService{private faultMode="normal";private leakedBuffers:Buffer[]=[];constructor(private readonly repository:PaymentRepository,private readonly notifications:NotificationClient){setInterval(()=>this.leakTick(),1000).unref();}
async authorize(input:CreatePayment,traceId="",traceparent?:string):Promise<Payment>{if(!Number.isFinite(input.amount)||input.amount<=0)throw new Error("amount must be positive");const existing=this.repository.findByIdempotencyKey(input.idempotencyKey);if(existing)return existing;const payment:Payment={id:randomUUID(),orderId:input.orderId,amount:input.amount,status:"AUTHORIZED",idempotencyKey:input.idempotencyKey,createdAt:new Date().toISOString()};this.repository.save(payment);try{await this.notifications.sendPaymentEvent(payment.id,payment.orderId,traceparent);}catch(error){log("WARN","payment notification failed",traceId,{error:String(error),payment_id:payment.id});}return payment;}
status(id:string):Payment{const payment=this.repository.findById(id);if(!payment)throw new Error("payment not found");return payment;}refund(id:string):Payment{const payment=this.status(id);if(payment.status==="REFUNDED")return payment;return this.repository.update({...payment,status:"REFUNDED"});}
setFault(mode:string):boolean{if(!["normal","memory_leak","promise_backlog","event_loop_blocking"].includes(mode))return false;this.faultMode=mode;if(mode==="normal"){this.leakedBuffers=[];leakedBytes.labels("payment-service",config.version,config.podName).set(0);}return true;}getFault():string{return this.faultMode;}
/** Allocate external Buffer memory so the Kubernetes limit causes a genuine OOMKill. */
private leakTick():void{if(this.faultMode!=="memory_leak")return;this.leakedBuffers.push(Buffer.alloc(6*1024*1024,1));leakedBytes.labels("payment-service",config.version,config.podName).set(this.leakedBuffers.length*6*1024*1024);log("WARN","retaining buffer for SRE-005","",{retained_mb:this.leakedBuffers.length*6});}}
