apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes: [ReadWriteOnce]
  {{- with .Values.inventoryPersistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.inventoryPersistence.size }}
