apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-lab
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  type: {{ $svc.serviceType }}
  selector: {app: {{ $name }}}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http
      {{- if eq $svc.serviceType "NodePort" }}
      nodePort: {{ $svc.nodePort }}
      {{- end }}
{{- end }}
